### ISSUE TITLE
Support preclustering filtering

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/supercluster#11]
Allow users to filter features before they are clustered.

cc @lyzidiamond @mourner

**Comment by mourner** [comment]
I don't think this should be done on the supercluster side — you can just do `geojson.features.filter(function () { ... })` before passing the result to supercluster. If we need this on the GL JS side, let's open a ticket there.

**Comment by lucaswoj** [comment]
Agreed. Bringing in `feature-filter` as a dep of supercluster doesn't make much sense. I opened an upstream ticket.

**Comment by strech345** [comment]
so how does it the filtering for clusters from geojson works?
Please give a example

**Comment by Nogginboink** [comment]
I'm not a Javascript expert, but I'm curious about the ramifications of filtering geoJSON points before passing the result to supercluster. 

Let's say I want my user to be able to filter results in the GUI. If I have to filter before passing the results to SC, does that mean I need to keep two copies of my data? I'd need to keep one copy of the full dataset (so that I can apply filters to it each time the user changes filtering criteria), and then a second copy of just the filtered data that I pass to supercluster. For a dataset of hundreds of thousands or millions of points, that's a lot of memory spent on two copies of data, isn't it?

If supercluster did the filtering internally with a filter() property, then only one copy of the data would have to be kept in memory. (Although clusters would of course have to be recomputed when filters are applied.)

I may be misunderstanding how Javascript manages memory in this scenario. If I am, I apologize.
