### ISSUE TITLE
No default export in dist code

### ISSUE THREAD

**Issue by sheerun** [mapbox/supercluster#120]
Hello,

It seems you by mistake published dist code without "default" export that you declare in original file:

```
> const supercluster = require('supercluster')
> supercluster.default
undefined
> supercluster
[Function: Supercluster]
```

**Comment by mourner** [comment]
The only export is the [Supercluster class](https://github.com/mapbox/supercluster/blob/master/index.js#L19), and this is the expected behavior.

**Comment by sheerun** [comment]
No, you do `export default class Supercluster` in source. Should I remove it?

**Comment by sheerun** [comment]
`export default` should export `.default` field for CommonJS compatiblity. There are many symptoms of not exporting it, for example: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34443 or unability to use `import Supercluster from 'supercluster'` with TypeScript, like you mentioned in the readme. Definitely there is default export and it's definitely not set in dist file.

**Comment by sheerun** [comment]
Please try any other universal library, and you'll discover each of them exports `default` field:

```
> require('cross-fetch')
{ [Function: fetch]
  fetch: [Circular],
  Headers: [Function: Headers],
  Request: [Function: Request],
  Response: [Function: Response],
  default: [Circular] }
```

Could you reopen?

**Comment by mourner** [comment]
Exporting the default with `module.exports = ` is the default behavior of [Rollup](https://github.com/rollup/rollup) for bundling `umd`, and consequently all the libraries with a single default export that use it for bundling. If you think this is wrong, submit a ticket there.

`cross-fetch` is [not a ES module](https://github.com/lquixada/cross-fetch/blob/master/src/node-ponyfill.js#L19-L20), Supercluster is. Perhaps the TypeScript configuration you use for Supercluster is not correct? I don't know much about TypeScript interoperability issues because I don't use it, but I've never seen JS packages with ES source code that manually patch in `default` for TS compatibility. 

So far I'm not convinced this is a Supercluster issue, but I'll reopen if there are convincing arguments.
