### ISSUE TITLE
One of the dependencies cannot be compiled by core-js ( Angular7 ).

### ISSUE THREAD

**Issue by CharlesYuCH** [mapbox/supercluster#122]
I used "mapbox-gl" and "ngx-mapbox-gl" in my project.
But in the compiled "vendor.js" file, "/node_modules/kdbush/src/index.js" was not compiled into ES5.
I've checked "polyfills.ts" and it's okay. All files except "kdbush" can be compiled correctly.
Can you see what's going on here.
![image](https://user-images.githubusercontent.com/48544185/57759532-b591ac00-772c-11e9-8442-7cff0fe9d03c.png)

**Comment by CharlesYuCH** [comment]
Oh, and. Thank you!

**Comment by mourner** [comment]
This is expected. What flavor of JS the Supercluster dependencies are shouldn't be a concern for any downstream consumers, because what Supercluster exposes publicly (in the `main` package field) is a single, dependency-less transpiled build. If your setup doesn't use that, it's a problem of your tooling / setup.
