### ISSUE TITLE
Informations about nodeSize

### ISSUE THREAD

**Issue by theochampion** [mapbox/supercluster#138]
Hi there,

It say in the docs that `nodeSize` is "the size of the KD-tree leaf node" and that it affects performance.

I was just wondering what is the result of changing it (up or down) and how does it affect performance?

Cheers!

**Comment by mourner** [comment]
This is a difficult question to answer — basically, increasing the size of the leaf node makes indexing faster but search slower, and vise versa. Since both are involved in clustering, whether setting it higher or lower speeds things up will depend on data size, distribution of points etc. So my recommendation is to stick to the default, or try experimenting to see if it improves anything in your case.
