### ISSUE TITLE
How can I use methods like  getClusterExpansionZoom( ) and getChildren( ) with Mapbox GL JS API?

### ISSUE THREAD

**Issue by StephenHanzlik** [mapbox/supercluster#60]
It is my understanding that Supercluster has been integrated into Mapbox GL JS but I am unable to figure out how to access the recently added methods, specifically, getClusterExpansionZoom( ) & getChildren( ) .   Is it necessary to use the library?   If so is the provided code compatible with the Mapbox GL JS API or only Leaflet?   Thank you

**Comment by bdoyle522** [comment]
@StephenHanzlik yeah I resolved to importing the supercluster library separately to access those methods. i added the cluster onto the GL map as normal, then on the 'click' event for the cluster I had to recreate the supercluster with my geojson in order to use those methods. not ideal, but it works.

**Comment by StephenHanzlik** [comment]
@bdoyle522 thanks for your input I will attempt this solution

**Comment by mourner** [comment]
This is tracked separately for GL JS in https://github.com/mapbox/mapbox-gl-js/issues/3318
