### ISSUE TITLE
getLeaves returns empty object

### ISSUE THREAD

**Issue by sidious18** [mapbox/supercluster#67]
getLeaves function in supercluster 3.0.0 returns an empty object instead of the points of a cluster. 2.3.0 works as intended.

**Comment by foundryspatial-duncan** [comment]
The [release notes for 3.0.0](https://github.com/mapbox/supercluster/releases/tag/v3.0.0) mentioned that the ids for clusters would be "different," but it didn't elaborate beyond that. 

> ⚠️ As a result of the change above, the same data will have different cluster_id numbers compared to previous releases.

In particular, I don't know how they're different, or how to get the new ids. That could be causing our problem, but I don't know how to fix. 

If you're using it with Mapbox GL, just FYI the latest version of Mapbox GL is still using Supercluster 2.3.0 internally, so I would think you'd want to stick with 2.3.0 so the `cluster_id`s line up.

**Comment by mourner** [comment]
Sorry for a late response. You can see in the Changelog that `getLeaves` has a different signature now — so instead of passing `clusterId, clusterZoom`, you just pass `clusterId`. Maybe that's what caused empty results for you.

> In particular, I don't know how they're different, or how to get the new ids. That could be causing our problem, but I don't know how to fix.

It doesn't matter how they're different — what matters is that Supercluster will generate cluster features with an `id` that you can later use for `getLeaves` and other methods. It shouldn't affect how you use Supercluster apart from the different `getLeaves` signature.

**Comment by mourner** [comment]
For future: if you're having an issue, please add minimal test cases that demonstrate the problem to your reports — without them, it's often impossible to diagnose.
