### ISSUE TITLE
Leaflet integration with layer state

### ISSUE THREAD

**Issue by hyperknot** [mapbox/supercluster#9]
The recommended Leaflet integration of clearLayers() + addData() on moveend discards any layer state on each map movement, so it is not possible to open a popup with `autoPan: true` for example, or to simply keep a popup open while panning the map (they would simply close on moveend).

One workaround is to save an id or hash of layers with open popups and try to loop through them and reopen each after addData(), but this is very inefficient and introduces quite a lot of client side code trying to load layer state on each move.

I believe that supercluster would prefer to be a framework independent tool, so a deeper Leaflet integration would probably need to stay out of this repo.

What is your plan and recommendation for supercluster in Leaflet?
- Should someone write a leaflet-supercluster wrapper which tries to implement state handling?
- If so, what would be your recommended architecture for it?

**Comment by mourner** [comment]
I'm not sure. Retaining the popups will probably need some additional boilerplate code, but it can't be inefficient because you only need to track a few popups at a time. Yes, I prefer not to have any integration code in the supercluster repository beyond the simple example that we have. So closing this as not actionable for now.
